In [1]:
%matplotlib osx
import matplotlib.pyplot as plt
import matplotlib.lines as ln
import numpy as np

plt.close()

plt.rcParams['font.family'] = 'Times New Roman'

step = 1
W_lb = 0
W_ub = 31
M = 32

fig = plt.figure(figsize=(10,4),dpi=300)
fig.patch.set_alpha(0.)

ax1 =fig.add_subplot(121)

n = np.arange(-10, 40, step)
w = np.ones(len(n))

l=len(n)
for i in range(l):
    if ((n[i] < W_lb) or (n[i] > W_ub)): w[i] = 'nan'
markerline, stemlines, baseline = plt.stem(n,w, color='k')
plt.setp(markerline, 'markerfacecolor', 'k')
plt.setp(stemlines, 'color', 'k')
plt.setp(baseline, 'color', 'k')

plt.xlim([-10, 40])
plt.ylim([0, 1.2])
plt.axhline(0, color='k', linewidth=2)
ax1.xaxis.set_label_coords(1.04, 0.05)
ax1.yaxis.set_label_coords(0.1,1.01)
plt.xlabel('$n$', fontsize=18)
plt.ylabel('$w[n]$', fontsize=18, rotation=0)
plt.xticks([-10, 0, 10, 20, 30, 40])
plt.yticks([0, 1])
plt.text(15, -0.25, '(a)', ha = 'center', va = 'center', fontsize=18)

# (b)
ax2 =fig.add_subplot(122)
omg = np.arange(-3-np.pi/4, 3+np.pi/4, 0.00001)
W = (np.sin((M/2)*omg)/np.sin((1/2)*omg))*np.exp(omg*(-(M-1)/2)*1j)
W_gain = np.absolute(W)
W_gain_max = np.max(W_gain)
plt.plot(omg, 20*np.log10(W_gain/W_gain_max), color='k')
#
plt.xlim([-3.5, 3.5])
plt.ylim([-103, 5])
plt.axhline(0, color='k', linewidth=0.1)

ax2.xaxis.set_label_coords(1.05, 0.05)
ax2.yaxis.set_label_coords(0.4,1.01)
plt.ylabel('$20\ \log_{10} (|W(\omega)|/W_{max})$', fontsize=18, rotation=0)
plt.xlabel('$\omega$', fontsize=18, rotation=0)
plt.xticks([0])
plt.yticks([0, -20, -40, -60,-80,-100])
plt.text(0, -125, '(b)', ha = 'center', va = 'center', fontsize=18)

plt.subplots_adjust(left=None, bottom=0.2, right=None, top=None, wspace=0.25, hspace=None)
plt.savefig('./figures/fig10.06.eps')
plt.show()


In [3]:
plt.close()


In [103]:
tmp = np.array([3+4j,1j])
test = np.exp(tmp)
print(tmp)
print(test)

[ 3.+4.j  0.+1.j]
[-13.12878308-15.20078446j   0.54030231 +0.84147098j]


In [20]:
import numpy as np

def win_rec(n, M=16, WB=0, fillzero=False):
  '''Rectangular window.
       n: discrete time. ndarray, int
       M: window size; dafault = 16
       WB: begin window; default = 0
       fillzero: value out of window; default value = nan

       return: rectangular window. ndarray'''
  
  l_n = len(n)
  w = np.ones(l_n)
  if (l_n <= 0):
    print("Argument n seems to be null.\n")
    return(None)

  W_lb = WB
  W_ub = M-1+WB
  if (fillzero == False): s = np.nan
  else: s = 0
  for i in range(l_n):
    if ((n[i] < W_lb) or (n[i] > W_ub)): w = s
  return(w)

def extract_by_win_rec(n, f, M=16, WB=0, fillzero=False):
  '''Signal extraction by Rectangular window.
       n: discrete time. ndarray, int
       f: function of n. ndarray, float
       M: window size; dafault = 16
       WB: begin window; default = 0
       fillzero: value out of window; default value = nan

       return: windowed f. ndarray'''
  
  l_n = len(n)
  l_f = len(f)
  f_tmp = np.array(f)
  if ((l_n <= 0) or (l_f <= 0)):
    print("Arguments n or f seem to be null.\n")
    return(None)
  elif (l_n != l_f):
    print("Length of n and f must be equal.")
    return(None)

  W_lb = WB
  W_ub = M-1+WB
  if (fillzero == False): s = np.nan
  else: s = 0
  for i in range(l_n):
    if ((n[i] < W_lb) or (n[i] > W_ub)): f_tmp[i] = s
  return(f_tmp)

def win_rec_spectral(M=16, omg_shift=0, l_range=-2*np.pi, r_range=2*np.pi, step=0.001):
  '''Rectangular window.
       M: window size; dafault = 16
       omg_shift: shift spectral to frequency by omg_shift; dafault = 0
       l_range= left of frequency range; default = -2*pi
       r_range= right of frequency range; default = 2*pi
       step: default=0.001

       return: Spectral of recutanglar window. ndarray'''

  omg = np.arange(l_range, r_range, step)
  W = (np.sin((M/2)*(omg-omg_shift))/np.sin((1/2)*(omg-omg_shift)))*np.exp((omg-omg_shift)*(-(M-1)/2)*1j)  

  return(W)
  
tmp = win_rec_spectral(16)
print(omg)
print(tmp)

[-3.5 -2.5 -1.5 -0.5  0.5  1.5]
[ 16.00000000 -8.62349420e-14j  15.99938001 -1.19997600e-01j
  15.99752012 -2.39980801e-01j ...,  15.99651595 +2.84441750e-01j
  15.99883530 +1.64467543e-01j  15.99991484 +4.44736004e-02j]


In [10]:
omg = np.arange(-3, 3, 1)
print(omg)
omg = omg - 0.5
print(omg)

[-3 -2 -1  0  1  2]
[-3.5 -2.5 -1.5 -0.5  0.5  1.5]


In [14]:
n = np.array(range(-3,3,1))
f = np.array(range(1,7,1))


[1 2 3 4 5 6]
